Week 4/Laborid/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_MVC.Models
{
    public class Employee
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Salary { get; set; }
    }
}

Week 4/Laborid/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Core;
using Facade;
using Infra;
using Microsoft.AspNetCore.Authorization;
using Laborid.Filters;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Laborid.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly SalesDbContext db;

        public EmployeeController(SalesDbContext db) { this.db = db; }
        
        public ActionResult Index()
        {
            
            var model = new EmployeeListViewModel();
            model.UserName = User.Identity.Name;
            var employees = Employees.Get(db);
            var list = new List<EmployeeViewModel>();
            foreach (var e in employees)
            {
                var employee = new EmployeeViewModel(e);
                employee.EmployeeID = e.EmployeeID;
                list.Add(employee);
            }
            model.Employees = list;
            model.FooterData = new FooterViewModel("TalTech");
            return View("Index", model);
        }

        [Authorize]
        [AdminFilter]
        public ActionResult AddNew()
        {
            return View("CreateEmployee", new CreateEmployeeViewModel());
        }

        [Authorize]
        [AdminFilter]
        [ValidateAntiForgeryToken]
        public ActionResult SaveEmployee(Employee e, string BtnSubmit)
        {
            if (BtnSubmit != "Save Employee") return RedirectToAction("Index");
            if (!ModelState.IsValid) return View("CreateEmployee");
            return save(e);
        }

        private ActionResult save(Employee e)
        {
            Employees emp = new Employees();
            emp.Save(e, db);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Employee employee = db.Employees.Find(id);
            if (employee == null) return NotFound();
            return View("Delete", employee);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await db.Employees.SingleOrDefaultAsync
                (m => m.EmployeeID == id);
            db.Employees.Remove(employee);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var employee = await db.Employees.SingleOrDefaultAsync(m => m.EmployeeID == id);
            if (employee == null) return NotFound();
            return View("Edit", employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("EmployeeID,FirstName,LastName,Salary")] Employee employee)
        {
            if (id != employee.EmployeeID) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(employee);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeID)) return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }

        private bool EmployeeExists(int id)
        {
            return db.Employees.Any(e => e.EmployeeID == id);
        }
    }
}

Week 4/Laborid/Views/Employee/NewLinkViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Laborid.Views.Employee
{
    public class NewLinkViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (HttpContext.Session.GetString("SessionKeyName") == "Admin") return View("AddNewLink");
            return Content(string.Empty);
        }
    }
}

Week 4/Laborid/Views/Employee/CreateEmployee.cshtml
@model Facade.CreateEmployeeViewModel

@{
    ViewBag.Title = "Create Employee";
    <script src="~/js/Validations.js"></script>
    <script>
        function ResetForm() {
            document.getElementById("TxtFName").value = "";
            document.getElementById("TxtLName").value = "";
            document.getElementById("TxtSalary").value = "";
        }
    </script>
}

<!DOCTYPE html>
<html>

<body>
    <h2>Create Employee</h2>
    <div>
        <form action="/Employee/SaveEmployee" method="post">
            @Html.AntiForgeryToken()
            <p>
                First Name: <input type="text" id="TxtFName" name="FirstName" value="" />
                @Html.ValidationMessage("FirstName")
            </p>
            <p>
                Last Name: <input type="text" id="TxtLName" name="LastName" value="" />
                @Html.ValidationMessage("LastName")
            </p>
            <p>
                Salary: <input type="text" id="TxtSalary" name="Salary" value="" />
                @Html.ValidationMessage("Salary")
            </p>
        
            <td colspan="2">
                <input type="submit" name="BtnSubmit" value="Save Employee" onclick="return IsValid();" />
                <input type="submit" name="BtnSubmit" value="Cancel" />
                <input type="button" name="BtnReset" value="Reset" onclick="ResetForm()" />
            </td>
        </form>
    </div>
</body>
</html>

Week 4/Laborid/Views/Employee/Delete.cshtml
@model Core.Employee

@{
    ViewBag.Title = "Delete";
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmployeeID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div> 

Week 4/Laborid/Views/Employee/Edit.cshtml
@model Core.Employee
@{
    ViewBag.Title = "Edit";
    <script src="~/js/Validations.js"></script>
}
<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div> 

Week 4/Laborid/Views/Employee/Index.cshtml
@using Facade

@model Facade.EmployeeListViewModel
@{
    ViewBag.Title = "Employees";
}

<!DOCTYPE html>

<html>
<h2>Employees</h2>
<body>
    <div style="text-align: right">
        Hello, @Model.UserName
        <a href="/Authentication/Logout">Logout</a>
    </div>
    <div>
        <p>
            @await Component.InvokeAsync("NewLink")
        </p>
        <table class="table">
            <tr>
                <th>Employee Name</th>
                <th>Salary</th>
            </tr>
            @foreach (var item in Model.Employees)
            {
            <tr>
                <td>@item.EmployeeName</td>
                <td style="background-color: @item.SalaryColor">@item.Salary</td>
                <td>
                    <a>
                        <a asp-action="Edit" asp-route-id="@item.EmployeeID">Edit</a> 
                        <a asp-action="Delete" asp-route-id="@item.EmployeeID">Delete</a>
                    </a>
                </td>
            </tr>
            }
        </table>
        @{
            Html.RenderPartial("Footer", Model.FooterData);
        }
    </div>
</body>
</html>